### ISSUE TITLE
.count defective in v 4.4.1

### ISSUE THREAD

**Issue by urecha** [vlvtin/vlquery#19]
Hello there

Since updating to version 4.4.1, the `.count` property throws following error for me:

```
(node:11544) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'rootLeaf' of undefined
    at Query.toSQL (...\server\node_modules\vlquery\dist\query.js:134:35)
    at Query.<anonymous> (...\server\node_modules\vlquery\dist\query.js:68:55)
    at Generator.next (<anonymous>)
    at ...\server\node_modules\vlquery\dist\query.js:8:71
    at new Promise (<anonymous>)
    at __awaiter (...\server\node_modules\vlquery\dist\query.js:4:12)
    at Query.toArrayRaw (...\server\node_modules\vlquery\dist\query.js:67:16)
    at Query.get count [as count] (...\server\node_modules\vlquery\dist\query.js:90:21)
    at DbSet.get count [as count] (...\server\node_modules\vlquery\dist\set.js:171:30)
    at QuizRepository.<anonymous> (...\server\dist\server\workareas\quiz\quiz.repository.js:24:46)
```

where in `quiz.repository.ts` I simply call 
```js
public async getCount(): Promise<number>{
		return await this.dbContext.quiz.count;
	}
```

I've tried it on two different projects, both running the latest VLQuery version, and on different entities as well as on PrimaryReferences and DbSets. All attempts ended with the same error.

My VlConfig looks like so:

```js
{
    "context": {
        "outFile": "db/db.context.ts",
        "runContext": true,
        "active": "_active",
        "connection": {
            "user": "<user>",
            "password": "<password>",
            "database": "<db>"
        },
        "audit": {
            "entity": "audit",
            "track": {
                "timestamp": "timestamp",
                "comment": "comment",
                "action": "action",
                "object": "object",
                "entity": "entity",
                "objectId": "id",
                "username": ["currentUser", "username"]
            },
            "commentRequired": true
        }
    }
```

DbContext doesn't have any errors.

Having had a look into the file in which the error is produced, it seems that the `this.onlyCount = true` statement in the getter
```js
get count() {
        this.onlyCount = true;
        return this.toArrayRaw().then(raw => raw[0].count);
    }
```

prevents the `includeClause` property to be set to anything, therefore causing the error when called in the return statement of the `toSQL` method.

Thanks in advance and just say the word if you need any more intel.

**Comment by levvij** [comment]
Fixed in 4.5.0

Warning: `.count` has been renamed to `.count()` to improve code legibility.
Please close the commit if this works in your application
